# Generated by Django 2.1.7 on 2019-02-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LighthouseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=2, null=True)),
                ('act', models.CharField(max_length=1, null=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
